version: '2.1'

services:
  db:
    restart: always
    image: postgres:11.6
    environment:      
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=puppies_dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flask_net
  
  app:
    build: .
    image: python-flask:latest
    ports:
      - 5000:80
    restart: always
    depends_on: 
      - db
    networks:
      - flask_net

networks:
  flask_net:

volumes:
  db-data: