version: '2.1'

services:
  db:
    restart: always
    image: postgres:11.6
    environment:      
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=puppies_dev
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
