"""added breed column

Revision ID: 55337c82d36b
Revises: 7946ab43a940
Create Date: 2019-12-09 13:11:09.237896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55337c82d36b'
down_revision = '7946ab43a940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
