"""first migration

Revision ID: 708a69ec454a
Revises: 
Create Date: 2019-12-09 16:44:30.445223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708a69ec454a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
